[package]
name = "s3"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = "1.17.1"
rand = "0.8"
rand_chacha = "0.3.1"


[[bin]]
name = "s3"
path = "src/main.rs"
